name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - test
          - pre
          - pro

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Asigna el entorno seleccionado al job para activar la protección
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to selected environment
        run: echo "Deploying to ${{ github.event.inputs.environment }} hello my cousin"

      - name: Conditional deployment step
        if: ${{ github.event.inputs.environment == 'pre' || github.event.inputs.environment == 'pro' }}
        run: echo "Approval required for deployment to ${{ github.event.inputs.environment }} environment"
